---
galaxy_info:
  author: Marcos Silvestrini
  description: Role for Setup Active Directory
  company: Silvestrini
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: Windows Server Standart Core
      versions:
        - 2019
  galaxy_tags:
    - Active Directory
    - DNS Server
    - Windows Server 2019
    - Vagrant
    - Powershell

dependencies: []