---
- name: Set Default DNS
  win_shell: |
    $publicInfos = Get-NetIPAddress | Where-Object { $_.IPAddress -like "*{{ netID }}*"}
    Set-DNSClientServerAddress –InterfaceIndex $publicInfos.InterfaceIndex –ServerAddresses "{{ dns1 }}", "{{ dns2 }}"

- name: Create Primary Zone
  win_shell: |
    Add-DnsServerPrimaryZone -Name "{{ ad_server_name }}.{{ domain_name }}" -ReplicationScope "Domain" -PassThru
  ignore_errors: True

- name: Create Reverse Lookup Zone
  win_shell: |
    Add-DnsServerPrimaryZone -NetworkID "{{ netID }}.0/24" -ReplicationScope "Domain"
    # Get-DnsServerZone
  ignore_errors: True

- name: Create (A IPv4Address) Host Records
  win_shell: |
    Add-DnsServerResourceRecordA -Name "{{ client_server_name }}" -ZoneName "{{ domain_name }}" -IPv4Address "{{ client_ip }}"
    # Get-DnsServerResourceRecord -ZoneName "{{ domain_name }}" -RRType A
  ignore_errors: True

- name: Create PTR Reverse Zone
  win_shell: |
    Add-DnsServerResourceRecordPtr `
    -Name "132" `
    -PtrDomainName "{{ ad_server_name }}.{{ domain_name }}" `
    -ZoneName "0.168.192.in-addr.arpa" `
    -computerName "{{ domain_name }}"
  ignore_errors: True