---
- name: Set DNS
  win_shell: |
    $netInfos = Get-NetIPAddress | Where-Object { $_.IPAddress -like "*192.168.0*" }
    $dns1          = $netInfos.IPAddress
    $dns2          = '1.1.1.1'

    Set-DNSClientServerAddress –InterfaceIndex $netInfos.InterfaceIndex –ServerAddresses $dns1,$dns2

- name: Join Server in Domain
  win_domain_membership:
    dns_domain_name: '{{ domain_name }}'
    domain_admin_user: '{{ user }}'
    domain_admin_password: '{{ password }}'
    state: domain