---
- name: Set DNS
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '{{ dns1 }}'
    - '{{ dns1 }}'

- name: Join Server in OU's
  win_domain_membership:
    dns_domain_name: '{{ domain_name }}'
    hostname: '{{ client_server_name }}'
    domain_admin_user: '{{ domain_user }}'
    domain_admin_password: '{{ password }}'
    domain_ou_path: '{{ item }}'
    state: domain
  loop: '{{ domain_ou_path }}'